### PR TITLE
Customize root url

### PR DESCRIPTION
**Pull request by picsoung**
Use case that I faced:

my `Meteor.absoluteUrl()` returns my AWS instance URL instead of my domain name.

I added the possibility of setting up `sitemaps.ROOT_URL` in `sitemaps.js`.

Now I can generate sitemaps with my domain name.

Thanks

### CODE REVIEW

**Comment by gadicc** [comment]
Considering the multitude of issues opened about the URL, I think many users will appreciate this simple patch.  Thanks!

**Comment by gadicc** [comment]
In the end I went for a slightly different API:

    sitemaps.config('rootUrl', 'customRootUrl');

It's available in v0.0.21.  Thanks again for the PR.

**Comment by picsoung** [comment]
Awesome :)

Thanks for your reactivity!

**Comment by gadicc** [comment]
Heh, 5 weeks, but got to it eventually.  Thanks for your patience!

**Pull request merged**
