### PR TITLE
Gzip compression support

### PR DESCRIPTION
**Pull request by nlhuykhang**
- Gzip compression support
- Edit README to show how to turn compression on
- Add test cases for compression

### CODE REVIEW

**Comment by nlhuykhang** [comment]
@gadicc Could you take a look at this PR?

**Comment by gadicc** [comment]
@nlhuykhang!  Thanks for the bump and for another great PR!  With README, tests and same API.

I think in the future we can make gzip the default; Meteor did the same without too much trouble.  We can keep it opt-in for now and make sure there are no problems, but I can't imagine anything going wrong.

Do you have any other work on this planned? :)  As I guess you noticed, I'm struggling to maintain this, especially since I'm not currently using it in any projects (Meteorpedia is locked on a much older version of Meteor).  I would love to add you as a maintainer if you're game.

**Comment by nlhuykhang** [comment]
@gadicc 

I have one project currently using this package. I think it will come to require sitemap index sooner or later so I will work on that feature too, so there will be a PR for that feature soon.

About being maintainer, I am not so sure. All my projects are now using Meteor 1.3 and higher, not sure if I could handle issues related to older versions.

**Comment by gadicc** [comment]
Haha ok no worries.  Any future PRs from you will be very welcome.  Thanks!

**Pull request merged**
